databases:
  - name: db
    databaseName: mydatabase
    user: username
    postgresMajorVersion: 13
    ipAllowList: []

services:
  - type: redis
    name: redis
    ipAllowList: []

  - type: web
    name: frontend
    env: docker
    dockerContext: ./frontend
    dockerfilePath: ./frontend/Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: "80"

  - type: web
    name: backend
    env: docker
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: db
          property: connectionString
      - key: REDIS_HOST
        fromService:
          name: redis
          type: redis

  - type: web
    name: nginx
    env: docker
    dockerContext: ./nginx
    dockerfilePath: ./nginx/Dockerfile
    startCommand: nginx -g "daemon off;"
    plan: free
    envVars:
      - key: PORT
        value: "80"
    dependsOn:
      - frontend
      - backend

  - type: worker
    name: celery-worker
    env: docker
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    startCommand: celery -A celery_tasks worker --loglevel=info
    plan: free
    envVars:
      - key: REDIS_HOST
        fromService:
          name: redis
          type: redis
      - key: DATABASE_URL
        fromDatabase:
          name: db
          property: connectionString

  - type: web
    name: flower
    env: docker
    dockerfilePath: ./Dockerfile-flower
    plan: free
    startCommand: flower --port=5555
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          name: redis
          type: redis

  - type: web
    name: pgadmin
    env: docker
    dockerfilePath: ./Dockerfile-pgadmin
    plan: free
    envVars:
      - key: PGADMIN_DEFAULT_EMAIL
        value: admin@admin.com
      - key: PGADMIN_DEFAULT_PASSWORD
        value: admin

volumes:
  - name: pgdata
    disk: 1GB
